In [1]:
import os 
import fastf1
import pandas as pd
import json

In [2]:

os.makedirs("cache", exist_ok=True)
fastf1.Cache.enable_cache("cache")

session = fastf1.get_session(2024, "Bahrain", "R")

session.load()

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']

In [3]:
# Filter and print all available attributes that hold data or DataFrames
attributes = [attr for attr in dir(session) if not attr.startswith('_')]

for attr in attributes:
    # Check if the attribute is a pandas DataFrame or similar data container
    obj = getattr(session, attr)
    if hasattr(obj, 'shape') or isinstance(obj, (dict, list)):
        print(f"session.{attr}")

session.car_data
session.drivers
session.event
session.f1_api_support
session.laps
session.pos_data
session.race_control_messages
session.results
session.session_info
session.session_status
session.track_status
session.weather_data

In [4]:
# binding tables datas for its names in python in pandas
car_data = session.car_data
driver = session.drivers
event = session.event
f1_api = session.f1_api_support
lap = session.laps
position = session.pos_data
control_sms = session.race_control_messages
result = session.results
session_info = session.session_info
session_status = session.session_status
track_status = session.track_status
weather = session.weather_data

In [5]:
# Created the  dictionary or list of my bound variables with their names
variables = {
    "car_data": car_data,
    "driver": driver,
    "event": event,
    "f1_api": f1_api,
    "lap": lap,
    "position": position,
    "control_sms": control_sms,
    "result": result,
    "session_info": session_info,
    "session_status": session_status,
    "track_status": track_status,
    "weather": weather
}

# Print the name and the exact data type for each one
for name, var in variables.items():
    print(f"{name:15} -> {type(var)}")

car_data        -> <class 'dict'>
driver          -> <class 'list'>
event           -> <class 'fastf1.events.Event'>
f1_api          -> <class 'numpy.bool_'>
lap             -> <class 'fastf1.core.Laps'>
position        -> <class 'dict'>
control_sms     -> <class 'pandas.core.frame.DataFrame'>
result          -> <class 'fastf1.core.SessionResults'>
session_info    -> <class 'dict'>
session_status  -> <class 'pandas.core.frame.DataFrame'>
track_status    -> <class 'pandas.core.frame.DataFrame'>
weather         -> <class 'pandas.core.frame.DataFrame'>

## driver and events are lists

In [6]:
# the only list data
print(driver)

['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']

In [7]:
# the evenets informations 
print(event)

RoundNumber                                                   1
Country                                                 Bahrain
Location                                                 Sakhir
OfficialEventName    FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2024
EventDate                                   2024-03-02 00:00:00
EventName                                    Bahrain Grand Prix
EventFormat                                        conventional
Session1                                             Practice 1
Session1Date                          2024-02-29 14:30:00+03:00
Session1DateUtc                             2024-02-29 11:30:00
Session2                                             Practice 2
Session2Date                          2024-02-29 18:00:00+03:00
Session2DateUtc                             2024-02-29 15:00:00
Session3                                             Practice 3
Session3Date                          2024-03-01 15:30:00+03:00
Session3DateUtc                             2024-03-01 12:30:00
Session4                                             Qualifying
Session4Date                          2024-03-01 19:00:00+03:00
Session4DateUtc                             2024-03-01 16:00:00
Session5                                                   Race
Session5Date                          2024-03-02 18:00:00+03:00
Session5DateUtc                             2024-03-02 15:00:00
F1ApiSupport                                               True
Name: 1, dtype: object

## f1_api have only value boolean true

In [8]:
print(f1_api)   # just a boolean data

True

# main tables
* lap
* control_sms
* results
* session_status
* track_status
* weather

In [27]:
lap.shape

(1129, 31)

In [28]:
# Count how many columns of each data type exist in the laps DataFrame
print(lap.dtypes.value_counts())

timedelta64[ns]    11
float64             8
object              6
bool                5
datetime64[ns]      1
Name: count, dtype: int64

In [29]:
lap.info()

<class 'fastf1.core.Laps'>
RangeIndex: 1129 entries, 0 to 1128
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                1129 non-null   timedelta64[ns]
 1   Driver              1129 non-null   object
 2   DriverNumber        1129 non-null   object
 3   LapTime             1127 non-null   timedelta64[ns]
 4   LapNumber           1129 non-null   float64
 5   Stint               1129 non-null   float64
 6   PitOutTime          43 non-null     timedelta64[ns]
 7   PitInTime           43 non-null     timedelta64[ns]
 8   Sector1Time         1108 non-null   timedelta64[ns]
 9   Sector2Time         1129 non-null   timedelta64[ns]
 10  Sector3Time         1129 non-null   timedelta64[ns]
 11  Sector1SessionTime  1107 non-null   timedelta64[ns]
 12  Sector2SessionTime  1129 non-null   timedelta64[ns]
 13  Sector3SessionTime  1129 non-null   timedelta64[ns]
 14  SpeedI1             1129 non-null   float64
 15  SpeedI2             1129 non-null   float64
 16  SpeedFL             1086 non-null   float64
 17  SpeedST             1129 non-null   float64
 18  IsPersonalBest      1129 non-null   bool
 19  Compound            1129 non-null   object
 20  TyreLife            1129 non-null   float64
 21  FreshTyre           1129 non-null   bool
 22  Team                1129 non-null   object
 23  LapStartTime        1129 non-null   timedelta64[ns]
 24  LapStartDate        1129 non-null   datetime64[ns]
 25  TrackStatus         1129 non-null   object
 26  Position            1129 non-null   float64
 27  Deleted             1129 non-null   bool
 28  DeletedReason       1129 non-null   object
 29  FastF1Generated     1129 non-null   bool
 30  IsAccurate          1129 non-null   bool
dtypes: bool(5), datetime64[ns](1), float64(8), object(6), timedelta64[ns](11)
memory usage: 235.0+ KB

In [30]:
lap.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:01:37.489000,VER,1,0 days 00:01:37.284000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:41.266000,...,False,Red Bull Racing,0 days 00:59:59.911000,2024-03-02 15:03:42.342,12,1.0,False,,False,False
1,0 days 01:03:13.785000,VER,1,0 days 00:01:36.296000,2.0,1.0,NaT,NaT,0 days 00:00:30.916000,0 days 00:00:41.661000,...,False,Red Bull Racing,0 days 01:01:37.489000,2024-03-02 15:05:19.920,1,1.0,False,,False,True
2,0 days 01:04:50.538000,VER,1,0 days 00:01:36.753000,3.0,1.0,NaT,NaT,0 days 00:00:30.999000,0 days 00:00:41.966000,...,False,Red Bull Racing,0 days 01:03:13.785000,2024-03-02 15:06:56.216,1,1.0,False,,False,True
3,0 days 01:06:27.185000,VER,1,0 days 00:01:36.647000,4.0,1.0,NaT,NaT,0 days 00:00:30.931000,0 days 00:00:41.892000,...,False,Red Bull Racing,0 days 01:04:50.538000,2024-03-02 15:08:32.969,1,1.0,False,,False,True
4,0 days 01:08:04.358000,VER,1,0 days 00:01:37.173000,5.0,1.0,NaT,NaT,0 days 00:00:31.255000,0 days 00:00:42.056000,...,False,Red Bull Racing,0 days 01:06:27.185000,2024-03-02 15:10:09.616,1,1.0,False,,False,True

# control_sms

In [31]:
control_sms.shape

(69, 9)

In [33]:
print(control_sms.dtypes.value_counts())

object            6
datetime64[ns]    1
float64           1
int64             1
Name: count, dtype: int64

In [15]:
control_sms.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Time          69 non-null     datetime64[ns]
 1   Category      69 non-null     object
 2   Message       69 non-null     object
 3   Status        2 non-null      object
 4   Flag          37 non-null     object
 5   Scope         37 non-null     object
 6   Sector        7 non-null      float64
 7   RacingNumber  29 non-null     object
 8   Lap           69 non-null     int64
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 5.0+ KB

In [16]:
control_sms.head()

,Time,Category,Message,Status,Flag,Scope,Sector,RacingNumber,Lap
0,2024-03-02 14:06:41,Other,PINK HEAD PADDING MATERIAL MUST BE USED,None,None,None,NaN,None,1
1,2024-03-02 14:20:01,Flag,GREEN LIGHT - PIT EXIT OPEN,None,GREEN,Track,NaN,None,1
2,2024-03-02 14:30:01,Other,PIT EXIT CLOSED,None,None,None,NaN,None,1
3,2024-03-02 14:45:29,Other,RISK OF RAIN FOR F1 RACE IS 0%,None,None,None,NaN,None,1
4,2024-03-02 14:57:04,Drs,DRS DISABLED,DISABLED,None,None,NaN,None,1

In [17]:
control_sms.memory_usage()

Index           128
Time            552
Category        552
Message         552
Status          552
Flag            552
Scope           552
Sector          552
RacingNumber    552
Lap             552
dtype: int64

In [34]:
result.shape

(20, 22)

In [35]:
print(result.dtypes.value_counts())

object             14
float64             4
timedelta64[ns]     4
Name: count, dtype: int64

In [18]:
result.info()

<class 'fastf1.core.SessionResults'>
Index: 20 entries, 1 to 2
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        20 non-null     object
 1   BroadcastName       20 non-null     object
 2   Abbreviation        20 non-null     object
 3   DriverId            20 non-null     object
 4   TeamName            20 non-null     object
 5   TeamColor           20 non-null     object
 6   TeamId              20 non-null     object
 7   FirstName           20 non-null     object
 8   LastName            20 non-null     object
 9   FullName            20 non-null     object
 10  HeadshotUrl         20 non-null     object
 11  CountryCode         20 non-null     object
 12  Position            20 non-null     float64
 13  ClassifiedPosition  20 non-null     object
 14  GridPosition        20 non-null     float64
 15  Q1                  0 non-null      timedelta64[ns]
 16  Q2                  0 non-null      timedelta64[ns]
 17  Q3                  0 non-null      timedelta64[ns]
 18  Time                20 non-null     timedelta64[ns]
 19  Status              20 non-null     object
 20  Points              20 non-null     float64
 21  Laps                20 non-null     float64
dtypes: float64(4), object(14), timedelta64[ns](4)
memory usage: 3.6+ KB

In [19]:
result.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671c6,red_bull,Max,Verstappen,Max Verstappen,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:31:44.742000,Finished,26.0,57.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671c6,red_bull,Sergio,Perez,Sergio Perez,...,2.0,2,5.0,NaT,NaT,NaT,0 days 00:00:22.457000,Finished,18.0,57.0
55,55,C SAINZ,SAI,sainz,Ferrari,e8002d,ferrari,Carlos,Sainz,Carlos Sainz,...,3.0,3,4.0,NaT,NaT,NaT,0 days 00:00:25.110000,Finished,15.0,57.0
16,16,C LECLERC,LEC,leclerc,Ferrari,e8002d,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,4,2.0,NaT,NaT,NaT,0 days 00:00:39.669000,Finished,12.0,57.0
63,63,G RUSSELL,RUS,russell,Mercedes,27f4d2,mercedes,George,Russell,George Russell,...,5.0,5,3.0,NaT,NaT,NaT,0 days 00:00:46.788000,Finished,10.0,57.0

# session_status

In [20]:
session_status.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    5 non-null      timedelta64[ns]
 1   Status  5 non-null      object
dtypes: object(1), timedelta64[ns](1)
memory usage: 208.0+ bytes

In [40]:
session_status.head()

                    Time     Status
0 0 days 00:00:09.193000   Inactive
1 0 days 00:59:59.911000    Started
2 0 days 02:31:44.878000   Finished
3 0 days 02:36:15.245000  Finalised
4 0 days 02:36:15.245000       Ends

In [22]:
track_status.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Time     7 non-null      timedelta64[ns]
 1   Status   7 non-null      object
 2   Message  7 non-null      object
dtypes: object(2), timedelta64[ns](1)
memory usage: 296.0+ bytes

In [43]:
track_status.head(7)

                    Time Status   Message
0 0 days 00:10:06.010000      1  AllClear
1 0 days 01:00:16.400000      2    Yellow
2 0 days 01:00:20.890000      1  AllClear
3 0 days 01:00:46.461000      2    Yellow
4 0 days 01:00:53.481000      1  AllClear
5 0 days 01:15:24.819000      2    Yellow
6 0 days 01:16:15.962000      1  AllClear

In [44]:
weather.shape

(157, 8)

In [46]:
print(weather.dtypes.value_counts())

float64            5
timedelta64[ns]    1
bool               1
int64              1
Name: count, dtype: int64

In [24]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Time           157 non-null    timedelta64[ns]
 1   AirTemp        157 non-null    float64
 2   Humidity       157 non-null    float64
 3   Pressure       157 non-null    float64
 4   Rainfall       157 non-null    bool
 5   TrackTemp      157 non-null    float64
 6   WindDirection  157 non-null    int64
 7   WindSpeed      157 non-null    float64
dtypes: bool(1), float64(5), int64(1), timedelta64[ns](1)
memory usage: 8.9 KB

In [25]:
weather.head()

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:14.093000,18.9,46.0,1017.1,False,26.5,162,0.9
1,0 days 00:01:14.084000,18.9,46.0,1017.0,False,26.5,55,1.0
2,0 days 00:02:14.093000,18.9,46.0,1017.0,False,26.5,55,1.0
3,0 days 00:03:14.090000,18.9,45.0,1017.0,False,26.2,85,1.1
4,0 days 00:04:14.091000,18.9,46.0,1017.0,False,26.2,178,1.0

# dictionaries

In [57]:
print(car_data['1'].shape)

(34819, 10)

In [58]:
print(car_data['1'].dtypes.value_counts())

float64            3
int64              2
timedelta64[ns]    2
datetime64[ns]     1
bool               1
object             1
Name: count, dtype: int64

In [56]:
display(car_data['1'].info())

<class 'fastf1.core.Telemetry'>
RangeIndex: 34819 entries, 0 to 34818
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         34819 non-null  datetime64[ns]
 1   RPM          34819 non-null  float64
 2   Speed        34819 non-null  float64
 3   nGear        34819 non-null  int64
 4   Throttle     34819 non-null  float64
 5   Brake        34819 non-null  bool
 6   DRS          34819 non-null  int64
 7   Source       34819 non-null  object
 8   Time         34819 non-null  timedelta64[ns]
 9   SessionTime  34819 non-null  timedelta64[ns]
dtypes: bool(1), datetime64[ns](1), float64(3), int64(2), object(1), timedelta64[ns](2)
memory usage: 2.4+ MB

None

In [55]:
display(car_data['1'].head())

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2024-03-02 14:03:43.818,0.0,0.0,0,0.0,False,0,car,0 days 00:00:01.387000,0 days 00:00:01.387000
1,2024-03-02 14:03:44.018,0.0,0.0,0,0.0,False,0,car,0 days 00:00:01.587000,0 days 00:00:01.587000
2,2024-03-02 14:03:44.379,0.0,0.0,0,0.0,False,0,car,0 days 00:00:01.948000,0 days 00:00:01.948000
3,2024-03-02 14:03:44.619,0.0,0.0,0,0.0,False,0,car,0 days 00:00:02.188000,0 days 00:00:02.188000
4,2024-03-02 14:03:44.899,0.0,0.0,0,0.0,False,0,car,0 days 00:00:02.468000,0 days 00:00:02.468000

In [60]:
print(position['1'].shape)

(35994, 8)

In [61]:
print(position['1'].dtypes.value_counts())

float64            3
object             2
timedelta64[ns]    2
datetime64[ns]     1
Name: count, dtype: int64

In [62]:
print(position['1'].info())

<class 'fastf1.core.Telemetry'>
RangeIndex: 35994 entries, 0 to 35993
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         35994 non-null  datetime64[ns]
 1   Status       35994 non-null  object
 2   X            35994 non-null  float64
 3   Y            35994 non-null  float64
 4   Z            35994 non-null  float64
 5   Source       35994 non-null  object
 6   Time         35994 non-null  timedelta64[ns]
 7   SessionTime  35994 non-null  timedelta64[ns]
dtypes: datetime64[ns](1), float64(3), object(2), timedelta64[ns](2)
memory usage: 2.2+ MB
None

In [26]:
display(position['1'].head())

,Date,Status,X,Y,Z,Source,Time,SessionTime
0,2024-03-02 14:03:43.899,OnTrack,0.0,0.0,0.0,pos,0 days 00:00:01.468000,0 days 00:00:01.468000
1,2024-03-02 14:03:44.219,OnTrack,0.0,0.0,0.0,pos,0 days 00:00:01.788000,0 days 00:00:01.788000
2,2024-03-02 14:03:44.460,OnTrack,0.0,0.0,0.0,pos,0 days 00:00:02.029000,0 days 00:00:02.029000
3,2024-03-02 14:03:44.720,OnTrack,0.0,0.0,0.0,pos,0 days 00:00:02.289000,0 days 00:00:02.289000
4,2024-03-02 14:03:45.000,OnTrack,0.0,0.0,0.0,pos,0 days 00:00:02.569000,0 days 00:00:02.569000

# session_info

In [72]:
print(session_info)

{'Meeting': {'Key': 1229, 'Name': 'Bahrain Grand Prix', 'OfficialName': 'FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2024', 'Location': 'Sakhir', 'Country': {'Key': 36, 'Code': 'BRN', 'Name': 'Bahrain'}, 'Circuit': {'Key': 63, 'ShortName': 'Sakhir'}}, 'ArchiveStatus': {'Status': 'Generating'}, 'Key': 9472, 'Type': 'Race', 'Name': 'Race', 'StartDate': datetime.datetime(2024, 3, 2, 18, 0), 'EndDate': datetime.datetime(2024, 3, 2, 20, 0), 'GmtOffset': datetime.timedelta(seconds=10800), 'Path': '2024/2024-03-02_Bahrain_Grand_Prix/2024-03-02_Race/'}

In [73]:
lap.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:01:37.489000,VER,1,0 days 00:01:37.284000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:41.266000,...,False,Red Bull Racing,0 days 00:59:59.911000,2024-03-02 15:03:42.342,12,1.0,False,,False,False
1,0 days 01:03:13.785000,VER,1,0 days 00:01:36.296000,2.0,1.0,NaT,NaT,0 days 00:00:30.916000,0 days 00:00:41.661000,...,False,Red Bull Racing,0 days 01:01:37.489000,2024-03-02 15:05:19.920,1,1.0,False,,False,True
2,0 days 01:04:50.538000,VER,1,0 days 00:01:36.753000,3.0,1.0,NaT,NaT,0 days 00:00:30.999000,0 days 00:00:41.966000,...,False,Red Bull Racing,0 days 01:03:13.785000,2024-03-02 15:06:56.216,1,1.0,False,,False,True
3,0 days 01:06:27.185000,VER,1,0 days 00:01:36.647000,4.0,1.0,NaT,NaT,0 days 00:00:30.931000,0 days 00:00:41.892000,...,False,Red Bull Racing,0 days 01:04:50.538000,2024-03-02 15:08:32.969,1,1.0,False,,False,True
4,0 days 01:08:04.358000,VER,1,0 days 00:01:37.173000,5.0,1.0,NaT,NaT,0 days 00:00:31.255000,0 days 00:00:42.056000,...,False,Red Bull Racing,0 days 01:06:27.185000,2024-03-02 15:10:09.616,1,1.0,False,,False,True

# answers

# shape and grain 

## we have in cache 13 files for bahrain gp 2024 

and all of them is not  pandas format , some in only python data structures and they are short list , dicts etc..

driver          -> list 
event           -> list    

* f1_api          -> one value boolean true

* lap             -> pandas, (shape: 1129, 31)
        timedelta64[ns]    11
        float64             8
        object              6
        bool                5
        datetime64[ns]      1

  
* control_sms     -> pandas, (shape:69, 9)
        object            6
        datetime64[ns]    1
        float64           1
        int64             1



result          -> pandas (shape: 20, 22)
        object             14
        float64             4
        timedelta64[ns]     4




* session_status  -> pandas (shape: 5, 2 ) simple table
* track_status    -> pandas (shape:7, 3) simple table about time of flags

* weather         -> pandas (shape: 157, 8)
        float64            5
        timedelta64[ns]    1
        bool               1
        int64              1
    
# these are dictionary but with this code i plotted : display(position['1'].info())
* car_data        -> dict  (shape:34819, 10)
        float64            3
        int64              2
        timedelta64[ns]    2
        datetime64[ns]     1
        bool               1
        object             1

  
* position        -> dict ,shape(35994, 8)
        float64            3
        object             2
        timedelta64[ns]    2
        datetime64[ns]     1


* session_info    -> dict very simple dictionary short . general overall info